### ISSUE TITLE
High resolution content image

### ISSUE THREAD

**Issue by ArtoriaKawaii** [ChenDarYen/ArtFusion#5]
In Supplementary Material, part E. Additional Qualitative Results, you mention this work can apply on higher-dimensional content images, while keeping the size of the style images at 256x256.
Can you explain or given an example on how to modift the code to generate result using 512x512 content image and 256x256 style image?
Thanks.

**Comment by ChenDarYen** [comment]
Hi there, you can take a look at the last part in `notebooks/style_transfer.ipynb`. There is an example of high-resolution generating. Actually, you can use content images in any size that can be divided by 32.

**Comment by ArtoriaKawaii** [comment]
I think I miss that part while copying into my own .py file.
The code works great, thanks!
